name: CD

on:
  workflow_run:
    workflows: [ "CI" ]              # Debe coincidir con el nombre de tu workflow de CI
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy (Firebase + Render)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ===== FRONTEND → Firebase Hosting =====
      - name: Install deps (frontend)
        working-directory: frontend
        run: npm ci

      # (Opcional) Inyectar VITE_API_URL en build usando el secret BACKEND_URL
      - name: Create .env.production (Vite)
        working-directory: frontend
        run: |
          echo "VITE_API_URL=${{ secrets.BACKEND_URL }}" > .env.production

      - name: Build frontend (Vite)
        working-directory: frontend
        run: npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting (prod)
        working-directory: frontend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          if [ -f ../.firebaserc ]; then
            sed -i "s/FIREBASE_PROJECT_ID_AQUI/${FIREBASE_PROJECT_ID}/g" ../.firebaserc || true
          fi
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID"

      # ===== BACKEND → Render (Deploy Hook) =====
      - name: Trigger Render backend deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "No RENDER_DEPLOY_HOOK secret set"; exit 1;
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"

      - name: Post URLs summary
        run: |
          echo "### URLs de despliegue" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend: ${{ secrets.FRONTEND_URL || 'Configura FRONTEND_URL si quieres mostrarla aquí' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Backend:  ${{ secrets.BACKEND_URL  || 'Configura BACKEND_URL si quieres mostrarla aquí' }}" >> $GITHUB_STEP_SUMMARY
